---

apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: app
spec:
  generateSelector: true
  parentResource:
    apiVersion: devopstoolkitseries.com/v1
    resource: apps
  childResources:
  - apiVersion: apps/v1
    resource: deployments
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: InPlace
  - apiVersion: networking.k8s.io/v1
    resource: ingresses
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://app-controller.controllers/sync

---

apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: slack
spec:
  generateSelector: true
  parentResource:
    apiVersion: devopstoolkitseries.com/v1
    resource: apps
  hooks:
    sync:
      webhook:
        url: http://slack-controller.controllers:8080/slack
